# Generated by Django 5.1 on 2024-09-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_messagevisiteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='donnee',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='donnee',
            name='etat_de_grossesse',
            field=models.IntegerField(null=True),
        ),
    ]
