# Generated by Django 5.1 on 2024-09-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_donnee_age_donnee_etat_de_grossesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donnee',
            name='antecedentMedicaux',
        ),
        migrations.RemoveField(
            model_name='donnee',
            name='modeVie',
        ),
    ]
