# Generated by Django 5.1 on 2024-09-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_donnee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
